### NumPy

**Why NumPy?**

NumPy is the leading Python library for efficiently handling and processing numeric data, making it essential for tasks in data science, machine learning, and deep learning.

NumPy is essential for several reasons:

1. **Numeric Data Handling**: It provides efficient structures (like arrays) to store and manipulate numerical data, making it ideal for datasets that consist of metrics such as height, weight, and blood pressure.
    - Many datasets, such as medical records, contain numerical metrics (e.g height, weight, blood pressure).

2. **Deep Learning**: Most machine learning and deep learning algorithms require data in a numeric format. NumPy facilitates the conversion and processing of various data types into numeric arrays that algorithms can work with.
    - Most neural networks require numeric data or data that has been converted to a numeric form.

3. **Performance(Best Tool for Numeric Data)**: NumPy is highly optimized for numerical computations. Its operations are implemented in C, allowing for faster execution compared to standard Python lists, especially for large datasets.
    - NumPy is the most efficient and powerful Python library for handling and processing numeric data.


What NumPy does?

NumPy ***provides*** several key functionalities:

1. **Support for Arrays and Matrices**: It introduces multidimensional array objects (ndarray) that allow for efficient storage and manipulation of large datasets. These arrays can be one-dimensional (vectors), two-dimensional (matrices), or even higher-dimensional.

2. **Mathematical Functions**: NumPy offers a comprehensive collection of mathematical functions that can perform operations on arrays and matrices. This includes element-wise operations, statistical calculations, linear algebra functions, and more, enabling complex computations with ease.

What Are NumPy Arrays?

NumPy arrays are multidimensional containers that hold data in a grid format, similar to Python lists but with enhanced capabilities. They are specifically optimized for numerical data, allowing for efficient storage and manipulation.

Why Use NumPy Arrays?

1. **Better Performance**: NumPy arrays are designed for high performance, offering efficient memory usage and faster computation times compared to standard Python lists. This makes them ideal for large datasets and complex mathematical operations.

2. **Homogeneous Data Types**: Unlike Python lists, which can contain mixed data types, NumPy arrays require all elements to be of the `same` data type. This uniformity allows for more efficient processing and optimized performance during calculations.

### Ranged Data with `np.arange`

The `np.arange()` function generates arrays with evenly spaced values. It works similarly to Python's built-in `range()` function but returns a NumPy array instead of a list.

**Syntax**:


In [ ]:
np.arange(start, stop, step)



- **start**: The starting value of the sequence (inclusive).
- **stop**: The end value of the sequence (exclusive).
- **step**: The spacing between values (default is 1).

---

#### **Examples**

***Example 1: Generate an array from 0 to 9***


In [ ]:
import numpy as np

# Create an array with values from 0 to 9
array = np.arange(0, 10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


***Example 2: Generate an array with a step size***


In [11]:
# Create an array with values from 1 to 10 with a step size of 2
array_step = np.arange(1, 10, 2)
print(array_step)

[1 3 5 7 9]


***Example 3: Generate a range of floating-point ]numbers***

In [12]:
# Create an array with floating-point values
array_float = np.arange(0, 1, 0.2)
print(array_float)

[0.  0.2 0.4 0.6 0.8]




---

The `np.arange()` function is particularly useful for creating sequences of numbers for indexing, iteration, or numerical computations.

### Ranged Data with `np.linspace`

The `np.linspace()` function generates evenly spaced numbers over a specified interval. Unlike `np.arange()`, which uses a step size, `np.linspace()` specifies the number of points to generate.

`Evenly spaced numbers mean that the difference between consecutive numbers in the sequence is` ***constant***. `In other words, the numbers are distributed uniformly across the specified interval`

#### **Syntax**:


In [ ]:
np.linspace(start, stop, num)



- **start**: The starting value of the interval.
- **stop**: The end value of the interval.
- **num**: The number of evenly spaced points to generate (default is 50).

---

### **Examples**

***Example 1: Generate 5 evenly spaced numbers between 0 and 10***


In [4]:
import numpy as np

# Generate 5 evenly spaced numbers between 0 and 10
array = np.linspace(0, 10, 5)
print(array)
# Output: [ 0.   2.5  5.   7.5 10. ]

[ 0.   2.5  5.   7.5 10. ]


***Example 2: Generate 4 evenly spaced numbers between -1 and 1***


In [5]:
# Generate 4 evenly spaced numbers between -1 and 1
array = np.linspace(-1, 1, 4)
print(array)
# Output: [-1.         -0.33333333  0.33333333  1.        ]

[-1.         -0.33333333  0.33333333  1.        ]




---

The `np.linspace()` function is particularly useful for creating sequences of numbers for plotting, interpolation, or numerical computations.

### Reshaping Data with `np.reshape`

The `np.reshape()` function allows you to change the structure of a NumPy array without modifying its data. It is useful for converting arrays into different shapes, such as from 1D to 2D or 3D.

#### **Syntax**:


In [ ]:
np.reshape(array, new_shape)



- **array**: The input array to be reshaped.
- **new_shape**: A tuple specifying the desired shape. The total number of elements must remain the same.

---

### **Examples**

***Example 1: Reshape a 1D array into a 2D array***


In [6]:
import numpy as np

# Create a 1D array
array_1d = np.array([1, 2, 3, 4, 5, 6])

# Reshape it into a 2D array with 2 rows and 3 columns
array_2d = np.reshape(array_1d, (2, 3))
print(array_2d)
# Output:
# [[1 2 3]
#  [4 5 6]]

[[1 2 3]
 [4 5 6]]


***Example 2: Reshape a 1D array into a 3D array***


In [7]:
# Reshape it into a 3D array with shape (2, 1, 3)
array_3d = np.reshape(array_1d, (2, 1, 3))
print(array_3d)
# Output:
# [[[1 2 3]]
#  [[4 5 6]]]

[[[1 2 3]]

 [[4 5 6]]]




---

### Notes:
- The total number of elements in the original array must match the total number of elements in the reshaped array. For example, a 1D array with 6 elements can be reshaped into `(2, 3)` or `(3, 2)` but not `(2, 4)`.
- You can use `-1` in one dimension of the new shape to let NumPy automatically calculate its size based on the total number of elements.

#### Example with `-1`:


In [8]:
# Automatically calculate the number of rows
array_auto = np.reshape(array_1d, (-1, 2))
print(array_auto)
# Output:
# [[1 2]
#  [3 4]
#  [5 6]]

[[1 2]
 [3 4]
 [5 6]]




The `np.reshape()` function is widely used in data preprocessing, machine learning, and numerical computations to organize data into the required structure.

### Flattening Arrays with `np.flatten()`

Flattening transforms multi-dimensional arrays `into` one-dimensional arrays. This is useful when you need to process or analyze data in a linear format.

#### **Syntax**:


In [ ]:
array.flatten()



- **array**: The input NumPy array to be flattened.

---

### **Examples**

***Example 1: Flatten a 2D array***


In [9]:
import numpy as np

# Create a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Flatten the 2D array into a 1D array
array_flattened = array_2d.flatten()
print(array_flattened)
# Output: [1 2 3 4 5 6]

[1 2 3 4 5 6]


***Example 2: Flatten a 3D array***


In [10]:
# Create a 3D array
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Flatten the 3D array into a 1D array
array_flattened = array_3d.flatten()
print(array_flattened)
# Output: [1 2 3 4 5 6 7 8]

[1 2 3 4 5 6 7 8]




---

The `np.flatten()` method is particularly useful for simplifying data structures for operations that require a single-dimensional array.

### Transposing Data with `np.transpose()`

Transposing swaps rows and columns in a matrix. It is commonly used in data manipulation and mathematical computations.

#### **Syntax**:


In [ ]:
np.transpose(array)



- **array**: The input NumPy array to be transposed.

---

### **Examples**

***Example 1: Transpose a 2D array***


In [11]:
import numpy as np

# Create a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Transpose the 2D array
array_transposed = np.transpose(array_2d)
print(array_transposed)
# Output:
# [[1 4]
#  [2 5]
#  [3 6]]

[[1 4]
 [2 5]
 [3 6]]


***Example 2: Transpose a 3D array***


In [12]:
# Create a 3D array
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Transpose the 3D array (swap axes)
array_transposed = np.transpose(array_3d, axes=(1, 0, 2))
print(array_transposed)
# Output:
# [[[1 2]
#   [5 6]]
#  [[3 4]
#   [7 8]]]

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]




---

The `np.transpose()` function is particularly useful for reshaping data for analysis, machine learning, or mathematical operations.

### Using `np.zeros` and `np.ones`

NumPy provides functions to create arrays filled with zeros or ones, which are useful for initializing arrays in various numerical computations.

---

##### **Creating Arrays Filled with Zeros**

#### **Syntax**:


In [ ]:
np.zeros(shape)



- **shape**: A tuple specifying the dimensions of the array.

#### **Example**:


In [14]:
import numpy as np

# Create a 2x3 array filled with zeros
array_zeros = np.zeros((2, 3))
print(array_zeros)
# Output:
# [[0. 0. 0.]
#  [0. 0. 0.]]

[[0. 0. 0.]
 [0. 0. 0.]]




---

##### **Creating Arrays Filled with Ones**

#### **Syntax**:


In [ ]:
np.ones(shape)



- **shape**: A tuple specifying the dimensions of the array.

#### **Example**:


In [13]:
# Create a 3x2 array filled with ones
array_ones = np.ones((3, 2))
print(array_ones)
# Output:
# [[1. 1.]
#  [1. 1.]
#  [1. 1.]]

[[1. 1.]
 [1. 1.]
 [1. 1.]]




---

These functions are particularly useful for creating placeholder arrays or initializing weights in machine learning models.

### ***Essential NumPy Operations***

---

#### **A. Arithmetic Operations**

Perform arithmetic on NumPy arrays. Operations are applied element-wise.

**Example**:


In [15]:
import numpy as np

# Create two arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Perform arithmetic operations
print(array1 + array2)  # Output: [5 7 9]
print(array1 - array2)  # Output: [-3 -3 -3]
print(array1 * array2)  # Output: [4 10 18]
print(array1 / array2)  # Output: [0.25 0.4  0.5]

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]




---

#### **B. Non-Linear Functions**

Use exponential and logarithmic functions.

**Example**:


In [17]:
# Exponential function
array = np.array([1, 2, 3])
print(np.exp(array))  # Output: [ 2.71828183  7.3890561  20.08553692]

# Logarithmic function
print(np.log(array))  # Output: [0.  0.69314718 1.09861229]
print(np.log10(array))  # Output: [0.         0.30103    0.47712125]

[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]
[0.         0.30103    0.47712125]




---

#### **C. Matrix Multiplication**

Perform dot products and matrix multiplication using `np.matmul`.

**Example**:


In [18]:
# Create two matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Perform matrix multiplication
result = np.matmul(matrix1, matrix2)
print(result)
# Output:
# [[19 22]
#  [43 50]]

[[19 22]
 [43 50]]




---

These operations are fundamental for numerical computations, data analysis, and machine learning tasks.

### Random Number Generation

---

#### **1. Random Integers with `np.random.randint`**

The `np.random.randint()` function generates random integers in a specified range.

#### **Syntax**:


In [ ]:
np.random.randint(low, high=None, size=None)



- **low**: The lower bound (inclusive).
- **high**: The upper bound (exclusive). If `high` is `None`, the range is `[0, low)`.
- **size**: The number of random integers to generate. Can be a single integer or a tuple for multidimensional arrays.

---

#### **Examples**

**Example 1: Generate a single random integer**


In [ ]:
import numpy as np

# Generate a random integer between 0 and 10
random_int = np.random.randint(0, 10)
print(random_int)
# Output: A random integer between 0 and 9



**Example 2: Generate multiple random integers**


In [ ]:
# Generate 5 random integers between 1 and 20
random_integers = np.random.randint(1, 20, size=5)
print(random_integers)
# Output: An array of 5 random integers between 1 and 19



**Example 3: Generate a 2D array of random integers**


In [ ]:
# Generate a 2x3 array of random integers between 10 and 50
random_array = np.random.randint(10, 50, size=(2, 3))
print(random_array)
# Output: A 2x3 array with random integers between 10 and 49



---

The `np.random.randint()` function is widely used in simulations, testing, and generating random datasets for machine learning and data analysis.


#### **2. Utility Functions in `np.random`**

- **`np.random.seed()`**:  
  Sets the random seed to make results reproducible. Using the same seed ensures the same sequence of random numbers is generated.
    
  **Example**:

In [48]:

import numpy as np

np.random.seed(42)
print(np.random.randint(0, 10, size=5))
# Output: [6 3 7 4 6]


[6 3 7 4 6]


 **`np.random.shuffle()`**:  
  Shuffles the array in place along the first axis (rows for 2D arrays).  
  **Example**:

In [54]:

array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.random.shuffle(array)
print(array)
# Output: Rows shuffled randomly


[[7 8 9]
 [4 5 6]
 [1 2 3]]


---

#### **3. Distributions in `np.random`**

- **Uniform Distribution (`np.random.uniform`)**:  
  Generates random floats from a uniform distribution over `[low, high)`.  
  **Example**:

In [61]:
random_uniform = np.random.uniform(0, 5, size=5)
print(random_uniform)
# Output: Random floats between 0 and 1


[4.16597456 0.86682327 1.95530304 0.91118044 3.77680705]


- **Normal (Gaussian) Distribution (`np.random.normal`)**:  
  Generates random numbers from a normal distribution with mean `loc` and standard deviation `scale`.  
  **Example**:

In [62]:

random_normal = np.random.normal(loc=0, scale=1, size=5)
print(random_normal)
# Output: Random numbers from a normal distribution

[-1.3779393  -0.35311665 -0.46146572  0.06665728 -0.17628566]


#### **4. Custom Sampling with `np.random.choice`**

- **`np.random.choice()`**:  
  Randomly selects elements from array `a`. Use the `p` parameter to define custom probabilities for each element.  
  **Example**:

In [46]:
array = [1, 2, 3, 4, 5]
random_sample = np.random.choice(array, size=3, replace=False)
print(random_sample)
# Output: Randomly selected elements from the array

# With custom probabilities
random_sample_with_prob = np.random.choice(array, size=3, p=[0.1, 0.2, 0.3, 0.2, 0.2])
print(random_sample_with_prob)
# Output: Randomly selected elements with custom probabilities

[1 2 5]
[3 1 5]




These functions and distributions are essential for simulations, statistical modeling, and machine learning tasks.