## NumPy array

#### What is NumPy array?

A **NumPy array** is a powerful data structure provided by the NumPy library in Python. It is a grid of values, all of the same data type, and is indexed by a tuple of non-negative integers. NumPy arrays are similar to Python lists but are more efficient for numerical computations due to their optimized storage and operations.

### Key Features of NumPy Arrays:
1. **Homogeneous Data**: All elements in a NumPy array must be of the same data type (e.g., integers, floats).
2. **Multidimensional**: NumPy arrays can have one or more dimensions (1D, 2D, 3D, etc.).
3. **Efficient Operations**: NumPy arrays support element-wise operations, broadcasting, and vectorized computations, making them faster than Python lists for numerical tasks.
4. **Fixed Size**: Once created, the size of a NumPy array cannot be changed.

***Why Use NumPy Arrays?***

1. Better Performance: NumPy arrays are designed for high performance, offering efficient memory usage and faster computation times compared to standard Python lists. This makes them ideal for large datasets and complex mathematical operations.

2. Homogeneous Data Types: Unlike Python lists, which can contain mixed data types, NumPy arrays require all elements to be of the `same` data type. This uniformity allows for more efficient processing and optimized performance during calculations

***Example:***


In [ ]:
import numpy as np

# Create a 1D NumPy array
array_1d = np.array([1, 2, 3, 4, 5])
print(array_1d)
# Output: [1 2 3 4 5]

# Create a 2D NumPy array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d)
# Output:
# [[1 2 3]
#  [4 5 6]]

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]




NumPy arrays are widely used in data science, machine learning, and scientific computing due to their flexibility and performance.

## Methods for creating NumPy Array

### 1.Create Array Using Python List

To create a NumPy array using a Python list, you can use the `np.array()` function. This function converts a Python list into a NumPy array.

***Example 1: Create a 1D NumPy array from a Python list***


In [2]:
import numpy as np

# Create a Python list
python_list = [1, 2, 3, 4, 5]

# Convert the list to a NumPy array
array_1d = np.array(python_list)
print(array_1d)
# Output: [1 2 3 4 5]

[1 2 3 4 5]


***Example 2: Create a 2D NumPy array from a nested Python list***


In [6]:
# Create a nested Python list
nested_list = [[1, 2, 3], [4, 5, 6]]

# Convert the nested list to a NumPy array
array_2d = np.array(nested_list)
print(array_2d)
# Output:
# [[1 2 3]
#  [4 5 6]]

[[1 2 3]
 [4 5 6]]


## 2. Create an Array With np.arange()

To create a NumPy array using `np.arange()`, you can generate an array with evenly spaced values within a specified range. The function takes parameters such as start, stop, and step.

***Example 1: Create an array from 0 to 9***


In [3]:
import numpy as np

# Create an array with values from 0 to 9
array_range = np.arange(10)
print(array_range)
# Output: [0 1 2 3 4 5 6 7 8 9]

[0 1 2 3 4 5 6 7 8 9]


***Example 2: Create an array with a step size***


In [4]:
# Create an array with values from 1 to 9 with a step size of 2
array_step = np.arange(1, 10, 2)
print(array_step)
# Output: [1 3 5 7 9]

[1 3 5 7 9]




The `np.arange()` function is useful for creating sequences of numbers for indexing, iteration, or numerical computations.

### 3.Create an Array Using np.zeros()

To create a NumPy array using `np.zeros()`, you can generate an array filled with zeros. You need to specify the shape of the array as a tuple.

***Example 1: Create a 1D array of zeros***


In [7]:
import numpy as np

# Create a 1D array of zeros with 5 elements
array_1d = np.zeros(5)
print(array_1d)
# Output: [0. 0. 0. 0. 0.]

[0. 0. 0. 0. 0.]


***Example 2: Create a 2D array of zeros***


In [8]:
# Create a 2D array of zeros with 3 rows and 4 columns
array_2d = np.zeros((3, 4))
print(array_2d)
# Output:
# [[0. 0. 0. 0.]
#  [0. 0. 0. 0.]
#  [0. 0. 0. 0.]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]




The `np.zeros()` function is useful for initializing arrays with default values of zero, which can later be updated with specific values.

## Create an Array With np.random.rand()

To create a NumPy array using `np.random.rand()`, you can generate an array of random numbers between 0 and 1. The shape of the array is specified as arguments.

***Example 1: Create a 1D array of random numbers***


In [9]:
import numpy as np

# Create a 1D array of random numbers with 5 elements
random_1d = np.random.rand(5)
print(random_1d)
# Output: [0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ] (example output)

[0.55790855 0.59343116 0.35414334 0.33613939 0.24723099]


***Example 2: Create a 2D array of random numbers***


In [10]:
# Create a 2D array of random numbers with 2 rows and 3 columns
random_2d = np.random.rand(2, 3)
print(random_2d)
# Output:
# [[0.5488135  0.71518937 0.60276338]
#  [0.54488318 0.4236548  0.64589411]] (example output)

[[0.20682968 0.55468086 0.0766613 ]
 [0.72987805 0.507761   0.46234827]]




The `np.random.rand()` function is useful for generating random data for simulations, testing, or initializing weights in machine learning models.

## Create an Empty NumPy Array

To create an empty NumPy array, you can use the `np.empty()` function. This function creates an array without initializing its values. The values in the array are arbitrary and depend on the memory state.

***Example 1: Create a 1D empty array***


In [11]:
import numpy as np

# Create a 1D empty array with 5 elements
empty_1d = np.empty(5)
print(empty_1d)
# Output: [1. 2. 3. 4. 5.] (example output, values are uninitialized)

[0.55790855 0.59343116 0.35414334 0.33613939 0.24723099]


***Example 2: Create a 2D empty array***


In [12]:
# Create a 2D empty array with 2 rows and 3 columns
empty_2d = np.empty((2, 3))
print(empty_2d)
# Output:
# [[1. 2. 3.]
#  [4. 5. 6.]] (example output, values are uninitialized)

[[0.20682968 0.55468086 0.0766613 ]
 [0.72987805 0.507761   0.46234827]]




The `np.empty()` function is useful `when` you want to create an array and fill it with values later, without initializing it to any specific value initially.